[bin.api]
listen="0.0.0.0"
port=8080

[databases.default]
url="sqllite:///miniprogram.sqlite3"
connection_timeout=1
idle_timeout=600
max_lifetime=1800
max_connections=30
min_connections=2
acquire_timeout=3
